### ISSUE TITLE
Release of embedded-layout needs release of embedded-layout-macros

### ISSUE THREAD

**Issue by StefanBossbaly** [bugadani/embedded-layout#27]
Recently ` embedded-layout` was reved and released as `0.3.2`. In order for `#[derive(ViewGroup)]` to work with Enums, empty enum variants and unit structs you need to rev and release `embedded-layout-macros` as well.

**Comment by bugadani** [comment]
Thanks for pointing this out and sorry :) This just shows I probably shouldn't do releases by hand. I've released it as [0.2.1](https://crates.io/crates/embedded-layout-macros/0.2.1), let me know if you have other issues!
